### PR TITLE
Add an optional timeout for waiting

### PR DESCRIPTION
**Pull request by younata**

### CODE REVIEW

**Comment by cbguder** [comment]
What's are some use cases for this outside of network requests (which can be handled by NSURLSession's timeout)?

**Comment by younata** [comment]
Maybe loading a file locally? The main use case is network requests (which may or may not use NSURLSession - for example, an SMTP client couldn't use NSURLSession).

I made this pull requests specifically for https://github.com/younata/Sinope/blob/master/SinopeIntegrationTests/RepositoryIntegrationSpec.swift, which... does use NSURLSession.

**Comment by cbguder** [comment]
I see. For a local file load, I feel like you wouldn't want it to time out. The outcome of that operation should be deterministic (i.e. the file either fails to load or always loads after a finite amount of time). Network traffic is of course different, and making the same request twice can produce different results due to packet loss etc., but I think this should be handled in the network library.

**Comment by younata** [comment]
sure, I was hoping to impose the timeout without having to actually interact with the network library (and instead, abstracting that away from the consumer of this).

**Pull request closed without merging**
